version: "3"
services:
    db: 
        image: mysql:8.0.0
        ports: 
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=root"
            - "MYSQL_PASSWORD=root"
            - "MYSQL_DATABASE=api"
    ruby:
        build: .
        volumes:
            - .:/myapp
        ports:
            - "3000:3000"
        links:
            - "db"
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
